# Configuration for PR auto-labeling
# https://github.com/actions/labeler

# CI/CD and configuration
ci:
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'
    - any-glob-to-any-file: '*.yml'
    - any-glob-to-any-file: '*.yaml'

configuration:
  - changed-files:
    - any-glob-to-any-file: '*.toml'
    - any-glob-to-any-file: '*.json'

# Documentation
documentation:
  - changed-files:
    - any-glob-to-any-file: 'docs/**/*'
    - any-glob-to-any-file: '**/*.md'

# Source code by area
infrastructure:
  - changed-files:
    - any-glob-to-any-file: 'src/infrastructure/**/*'

domain:
  - changed-files:
    - any-glob-to-any-file: 'src/domain/**/*'

application:
  - changed-files:
    - any-glob-to-any-file: 'src/application/**/*'

# Exchange specific
exchange-integration:
  - changed-files:
    - any-glob-to-any-file: 'src/infrastructure/websocket/**/*'
    - any-glob-to-any-file: 'src/application/exchanges/**/*'

# Security
security:
  - changed-files:
    - any-glob-to-any-file: 'src/auth.rs'
    - any-glob-to-any-file: 'src/persistence/**/*'
    - any-glob-to-any-file: 'deny.toml'

# Tests
tests:
  - changed-files:
    - any-glob-to-any-file: 'tests/**/*'
    - any-glob-to-any-file: 'src/**/tests.rs'
    - any-glob-to-any-file: 'src/**/*_test.rs'

# Dependencies
dependencies:
  - changed-files:
    - any-glob-to-any-file: 'Cargo.toml'
    - any-glob-to-any-file: 'Cargo.lock'
