# cargo-deny configuration
# https://embarkstudios.github.io/cargo-deny/

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# Lint level for security vulnerabilities
vulnerability = "deny"
# Lint level for unmaintained crates
unmaintained = "warn"
# Lint level for crates with security notices
notice = "warn"
# Lint level for yanked crates
yanked = "deny"
# Ignore specific advisories
ignore = []

[licenses]
# Lint level for licenses
unlicensed = "deny"
# List of allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unlicense",
    "0BSD",
]
# Lint level for copyleft licenses
copyleft = "warn"
# Blanket approval or denial for OSI-approved or FSF Free/Libre licenses
allow-osi-fsf-free = "both"
# Lint level for licenses not in the allow list
default = "deny"
# Confidence threshold for license detection
confidence-threshold = 0.8

[bans]
# Lint level for multiple versions of the same crate
multiple-versions = "warn"
# Lint level for wildcard dependencies
wildcards = "warn"
# Allow certain crates to have multiple versions
skip = []
# List of crates that are banned
deny = []

[sources]
# Lint level for unknown sources
unknown-registry = "deny"
# Lint level for unknown git sources
unknown-git = "deny"
# Allow git sources from these hosts
allow-git = []
