# dYdX v4 Mainnet Configuration
# Updated with working endpoints from https://docs.dydx.xyz/nodes/resources

[node]
# Polkachu gRPC endpoint (300 req/m rate limit)
endpoint = "https://dydx-dao-archive-grpc-1.polkachu.com:443"
chain_id = "dydx-mainnet-1"
fee_denom = "adydx"

[indexer]
http.endpoint = "https://indexer.dydx.trade"
ws.endpoint = "wss://indexer.dydx.trade/vanalyse le code et decrit le comportement du system4/ws"
