# dYdX v4 Mainnet Configuration

[node]
endpoint = "https://dydx-ops-rpc.kingnodes.com:443"
chain_id = "dydx-mainnet-1"
fee_denom = "adydx"

[indexer]
http.endpoint = "https://indexer.dydx.trade"
ws.endpoint = "wss://indexer.dydx.trade/v4/ws"
